<?php
	if(!defined("DB_SERVER")){
		define("DB_SERVER","localhost");
	}
	if(!defined("DB_USER")){
		 define("DB_USER","ritu1");
	}
	if(!defined("DB_PASS")){
		 define("DB_PASS","ritusingla1");
	}
	if(!defined("DB_NAME")){
		 define("DB_NAME","photo_gallery");
	}
?>